### ISSUE TITLE
jasmineDone() expects rundetails object

### ISSUE THREAD

**Issue by innovate-invent** [rdy/jasmine-json-stream-reporter#9]
I am not sure if the bug is in this repository or jasmine-spec-reporter.
jasmine-spec-reporter expects an object with a 'order' property.

https://github.com/rdy/jasmine-json-stream-reporter/blob/1477c171e3703fa1498ad3504cbcb691cc53fabb/src/to-reporter.js#L43

```
TypeError: Cannot read property 'order' of undefined
    at ExecutionMetrics.stop (/home/nolan/Projects/socprox/node_modules/jasmine-spec-reporter/built/execution-metrics.js:27:34)
    at SpecReporter.jasmineDone (/home/nolan/Projects/socprox/node_modules/jasmine-spec-reporter/built/spec-reporter.js:54:22)
    at /home/nolan/Projects/socprox/node_modules/jasmine-json-stream-reporter/to-reporter.js:68:23
    at Array.forEach (<anonymous>)
    at DestroyableTransform._flush (/home/nolan/Projects/socprox/node_modules/jasmine-json-stream-reporter/to-reporter.js:67:15)
    at DestroyableTransform.prefinish (/home/nolan/Projects/socprox/node_modules/readable-stream/lib/_stream_transform.js:138:10)
    at DestroyableTransform.emit (events.js:315:20)
    at DestroyableTransform.EventEmitter.emit (domain.js:547:15)
    at prefinish (/home/nolan/Projects/socprox/node_modules/readable-stream/lib/_stream_writable.js:619:14)
    at finishMaybe (/home/nolan/Projects/socprox/node_modules/readable-stream/lib/_stream_writable.js:627:5)
    at endWritable (/home/nolan/Projects/socprox/node_modules/readable-stream/lib/_stream_writable.js:638:3)
    at DestroyableTransform.Writable.end (/home/nolan/Projects/socprox/node_modules/readable-stream/lib/_stream_writable.js:594:41)
    at Stream.onend (internal/streams/legacy.js:46:10)
    at Stream.emit (events.js:327:22)
    at Stream.EventEmitter.emit (domain.js:547:15)
    at drain (/home/nolan/Projects/socprox/node_modules/through/index.js:34:23)
    at Stream.stream.queue.stream.push (/home/nolan/Projects/socprox/node_modules/through/index.js:45:5)
    at /home/nolan/Projects/socprox/node_modules/flat-map/flat-map.js:64:21
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

**Comment by bcaudan** [comment]
FMU, `jasmineDone` must be called with a runDetails argument, cf [type](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/jasmine/v2/index.d.ts#L525) and [code](https://github.com/jasmine/jasmine/blob/b3ab9fad9d62ef72fa4851b690b56c06d86025c2/src/core/JsApiReporter.js#L24).
Otherwise, you get this kind of errors if one of the reporter need to use it.

**Comment by innovate-invent** [comment]
Can you link to any documentation? I need to forward this all to https://github.com/bcaudan/jasmine-spec-reporter/issues/512
